name: MSBuild

on:
  push:
    tags:
      - 'v*'
    branches:
      - '**'

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Configure CMake
        run: >
          cmake -B ${{ github.workspace }}/build
          -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
          -A Win32

      - name: Build
        run: >
          cmake --build ${{ github.workspace }}/build
          --config ${{ env.BUILD_TYPE }}

      - name: Move wkRealTime.dll to bundle
        shell: pwsh
        run: |
          Move-Item `
            "build/${{ env.BUILD_TYPE }}/wkRealTime.dll" `
            "bundle/wkZRealTime.dll"

      - name: Upload wkRealTime-release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: wkRealTime-release
          path: bundle/*
          retention-days: 10

      - name: Upload wkRealTime-pdb Artifact
        uses: actions/upload-artifact@v4
        with:
          name: wkRealTime-pdb
          path: build/${{ env.BUILD_TYPE }}/wkRealTime.pdb
          retention-days: 10

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    permissions:
      contents: write

    steps:
      - name: Download release artifact
        uses: actions/download-artifact@v4
        with:
          name: wkRealTime-release
          path: wkRealTime-release

      - name: Download pdb artifact
        uses: actions/download-artifact@v4
        with:
          name: wkRealTime-pdb
          path: wkRealTime-pdb

      - name: Create wkRealTime-release.zip
        run: |
          zip -r wkRealTime-release.zip ./wkRealTime-release

      - name: Create wkRealTime-pdb.zip
        run: |
          zip -r wkRealTime-pdb.zip ./wkRealTime-pdb

      - name: Create GitHub Release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            wkRealTime-release.zip
            wkRealTime-pdb.zip
